# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d80bd1d10b8410ad943b5a1f87bbdfcdde34dc024258072767c0d159cb67188e4639f9cf31baaaab7fe6380cb967d3fe2b3e77649accbbc379c5e57e7c1cf942

test:
  secret_key_base: 85b356c300f0f968a86ad4c3c2d1f4767d01cb6fe38041c018146a4138e3a7b206d7a7ae3d301bc88a17826dfd9cc041a8d46617be8c9daba05598f6d0467544

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
